apiVersion: hivemq.com/v1
kind: HiveMQCluster
metadata:
  name: hivemq-c
spec:
  hivemqVersion: k8s-4.8.4
  nodeCount: 2
  cpu: '2'
  memory: '2G'
  logLevel: INFO
  controllerTemplate: cluster-stateful-set.yaml
  operatorHints:
    statefulSet: 
      surgeNode: true
      surgeNodeCleanupPvc: true
  extensions:
  - configMap: kafka-ext-conf
    enabled: true
    extensionUri: preinstalled
    name: hivemq-kafka-extension
  configMaps:
  - name: hivemq-license
    path: /opt/hivemq/license
  ports:
  - name: "mqtt"
    port: 1883
    expose: true
    patch:
    - '[{"op":"add","path":"/spec/selector/hivemq.com~1node-offline","value":"false"},{"op":"add","path":"/metadata/annotations","value":{"service.spec.externalTrafficPolicy":"Local"}}]'
  - name: "cc"
    port: 8080
    expose: true
    patch:
    - '[{"op":"add","path":"/spec/sessionAffinity","value":"ClientIP"}]'
  - name: "api"
    port: 8888
    expose: true
    patch:
    - '[{"op":"add","path":"/spec/sessionAffinity","value":"ClientIP"}]'
  mqtt:
    maxQos: 2
    queuedMessagesMaxQueueSize: 2000

  monitoring:
    enablePrometheus: true
